{
  "comments": [
    {
      "key": {
        "uuid": "dabed58f_3c6d6005",
        "filename": "sdnvpn/lib/config.py",
        "patchSetId": 6
      },
      "lineNbr": 41,
      "author": {
        "id": 6527
      },
      "writtenOn": "2017-02-17T09:29:10Z",
      "side": 1,
      "message": "lines 41-46: I think, these lines are redundant",
      "revId": "580559b1cf5eae5bf7d266fd783640b0da8d14be",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}