{
  "comments": [
    {
      "key": {
        "uuid": "da33351e_a502143c",
        "filename": "sdnvpn/test/functest/testcase_11.py",
        "patchSetId": 3
      },
      "lineNbr": 158,
      "author": {
        "id": 2697
      },
      "writtenOn": "2017-08-22T12:15:44Z",
      "side": 1,
      "message": "shouldn\u0027t that be in the ovs logs? Or is  there a log in odl as well?",
      "range": {
        "startLine": 155,
        "startChar": 2,
        "endLine": 158,
        "endChar": 61
      },
      "revId": "ffa55d34dd58014a5f04387c5badbb9ae4a35444",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}